apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tsm-pik
  namespace: tsm
  labels:
    team: tsm

spec:
  port: 8080
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  kafka:
    pool: nav-dev
  liveness:
    path: /internal/health/alive
  readiness:
    path: /internal/health/ready
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
