[versions]
kotlin = "2.4.10"
logback = "1.6.3"
logbackEncoder = "9.0"
spotless = "8.10.0"
jackson = "3.2.2"
detekt = "2.0.0-alpha.6"
ktfmt = "0.62"
tsm-regula = "56"
jvmVersion = "25"
jsonSchemaValidator = "3.0.7"


[libraries]

# Monitoring and observability
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder" }

# Tsm dependencies
tsm-regula = { module = "no.nav.tsm.regulus:juridisk", version.ref = "tsm-regula" }

# Testing
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchemaValidator"}


# Transitive Vulnerabilities
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "dev.detekt",  version.ref = "detekt" }
